version: "3.8"
services:
  flask-service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - MYSQL_URI=mysql://root:root@mysql-db:3306/shopdb

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mysql-data:
